"""Write SergeMiddle/dsp/WaveMiddleTables.h from wave_middle.py and the tap CSVs.

Copyright (c) 2026 Martial Systems LLC. All rights reserved.

The header is generated, not edited. Every value is printed with repr, so the
C++ doubles are the same bits as the Python floats.

    python3 tools/gen_tables.py          # rewrite the header
    python3 tools/gen_tables.py --check  # exit 1 if the header is stale
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import wave_middle as wm  # noqa: E402

HEADER = ROOT / "SergeMiddle" / "dsp" / "WaveMiddleTables.h"


def _array(name: str, values) -> list[str]:
    lines = [f"inline constexpr double {name}[{len(values)}] = {{"]
    lines += [f"  {v!r}," for v in values]
    lines.append("};")
    return lines


def render() -> str:
    lines = [
        "// Generated by tools/gen_tables.py. Do not edit.",
        "// Copyright (c) 2026 Martial Systems LLC. All rights reserved.",
        "//",
        "// Source: wave_middle.py, halfband_taps.csv, upsample_taps.csv.",
        "",
        "#pragma once",
        "",
        "namespace serge",
        "{",
        "",
        f"inline constexpr int kDrivePeakCount = {len(wm.DRIVE_PEAKS)};",
        "",
    ]
    lines += _array("kDrivePeakG", [g for g, _ in wm.DRIVE_PEAKS])
    lines.append("")
    lines += _array("kDrivePeakP", [p for _, p in wm.DRIVE_PEAKS])
    lines.append("")
    lines.append(f"inline constexpr int kFirTaps = {wm.HALFBAND_TAPS_N};")
    lines.append("")
    lines.append("// Decimator, sum 1.")
    lines += _array("kHalfbandTaps", wm.HALFBAND_TAPS)
    lines.append("")
    lines.append("// 4x insert-and-filter, each tap 4 times the decimator, sum 4.")
    lines += _array("kUpsampleTaps", wm.UPSAMPLE_TAPS)
    lines += ["", "} // namespace serge", ""]
    return "\n".join(lines)


def main() -> int:
    text = render()
    if "--check" in sys.argv[1:]:
        current = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if current != text:
            print(f"{HEADER.relative_to(ROOT)} is stale; run tools/gen_tables.py")
            return 1
        return 0
    HEADER.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
