"""Write SergeMiddle/dsp/tests/chain_reference.csv from wave_middle.py.

Copyright (c) 2026 Martial Systems LLC. All rights reserved.

The full plugin path, composed from the Python reference in the order of
IPLUG2.md: smooth g, v = 5 g a, 4x upsample, six cells, 63-tap decimator,
decimate (phase 0), OUTPUT_GAIN * P(1) / P(g), 10 Hz block. The knob target
steps from 1 to 2 a quarter of the way in so the smoother is exercised.

    python3 tools/make_chain_fixture.py
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import wave_middle as wm  # noqa: E402

FIXTURE = ROOT / "SergeMiddle" / "dsp" / "tests" / "chain_reference.csv"
FS = 48000.0
N = 1024
FREQ = 1000.0
AMPLITUDE = 0.9


def main() -> int:
    a = [AMPLITUDE * math.sin(2.0 * math.pi * FREQ * i / FS) for i in range(N)]
    target = [1.0 if i < N // 4 else 2.0 for i in range(N)]
    coeff = wm.smooth_coeff(FS)
    g = wm.drive_scale(target[0])
    gs = []
    for t in target:
        g = wm.smooth_g(g, t, coeff)
        gs.append(g)
    volts = [wm.AUDIO_FULL_SCALE_VOLTS * wm.drive_scale(gi) * ai for gi, ai in zip(gs, a)]
    high, _ = wm.fir_run(wm.insert_zeros(volts), wm.UPSAMPLE_TAPS)
    cells = [wm.process(x) for x in high]
    low = wm.decimate(wm.fir_run(cells, wm.HALFBAND_TAPS)[0])
    bounded = [wm.output_scale(gi) * y for gi, y in zip(gs, low)]
    out, _ = wm.dc_block(bounded, FS)
    lines = ["# Generated by tools/make_chain_fixture.py. Do not edit.", "n,a,target,g,pre_dc,out"]
    lines += [
        f"{i},{a[i]!r},{target[i]!r},{gs[i]!r},{bounded[i]!r},{out[i]!r}"
        for i in range(N)
    ]
    FIXTURE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
